-- MangoRemote Seed Data

-- Categories
insert into categories (id, name, slug) values
  ('cat-ops', 'Operations', 'operations'),
  ('cat-health', 'Healthcare', 'healthcare'),
  ('cat-pm', 'Project Management', 'project-management'),
  ('cat-sales', 'Sales', 'sales'),
  ('cat-mktg', 'Marketing', 'marketing'),
  ('cat-support', 'Support', 'support'),
  ('cat-hr', 'HR & Recruiting', 'hr-recruiting'),
  ('cat-tech-support', 'Technical Support', 'technical-support'),
  ('cat-finance', 'Finance', 'finance'),
  ('cat-cs', 'Customer Success', 'customer-success'),
  ('cat-mgmt', 'Management', 'management')
on conflict (slug) do nothing;

-- Companies
insert into companies (id, name, slug, logo_url, website, verified) values
  ('co-storyteller', 'Storyteller', 'storyteller', null, 'https://storytellerapp.com', true),
  ('co-drcatalyst', 'DrCatalyst', 'drcatalyst', null, 'https://drcatalyst.com', true),
  ('co-finalsite', 'Finalsite', 'finalsite', null, 'https://finalsite.com', true),
  ('co-jumpcloud', 'JumpCloud', 'jumpcloud', null, 'https://jumpcloud.com', true),
  ('co-grafana', 'Grafana Labs', 'grafana-labs', null, 'https://grafana.com', true),
  ('co-5ca', '5CA', '5ca', null, 'https://jobs.5ca.com', true),
  ('co-airbnb', 'Airbnb', 'airbnb', null, 'https://airbnb.com', true),
  ('co-makersite', 'Makersite', 'makersite', null, 'https://makersite.io', true),
  ('co-elevenlabs', 'ElevenLabs', 'elevenlabs', null, 'https://elevenlabs.io', true),
  ('co-soundstack', 'SoundStack', 'soundstack', null, 'https://soundstack.com', true),
  ('co-varicent', 'Varicent', 'varicent', null, 'https://varicent.com', true),
  ('co-enode', 'Enode', 'enode', null, 'https://enode.com', true),
  ('co-mny', 'MNY Ventures', 'mny-ventures', null, null, true)
on conflict (slug) do nothing;

-- Jobs
insert into jobs (title, slug, company_id, description, salary_min, salary_max, salary_currency, apply_url, category_id, employment_type, tags, region_tags, is_premium, is_featured, status, source, asia_friendly, published_at, expires_at) values

  ('Client Delivery Operations',
   'client-delivery-operations-storyteller',
   'co-storyteller',
   'Join the Storyteller team as a Client Delivery Operations specialist. You will manage client onboarding, delivery workflows, and operational processes to ensure smooth SaaS deployments.',
   null, null, 'USD',
   'https://storyteller.applytojob.com/apply/LYGLEF4mTj/Client-Delivery-Operations',
   'cat-ops', 'full-time',
   ARRAY['entry-level', 'saas', 'operations'],
   ARRAY['Remote South Africa'],
   false, false, 'live', 'manual', false,
   now(), now() + interval '30 days'),

  ('Virtual Medical Assistant RN',
   'virtual-medical-assistant-rn-drcatalyst',
   'co-drcatalyst',
   'DrCatalyst is seeking a registered nurse to work as a Virtual Medical Assistant in a fully remote capacity. Support healthcare providers with clinical documentation, patient communication, and care coordination.',
   null, null, 'USD',
   'https://medspecializedinc.applytojob.com/apply/aKnd5U6IgE/Virtual-Medical-Assistant-RN-Remote',
   'cat-health', 'full-time',
   ARRAY['entry-level', 'healthcare', 'rn', 'nursing'],
   ARRAY['Remote Philippines'],
   false, true, 'live', 'manual', true,
   now(), now() + interval '30 days'),

  ('Project Manager',
   'project-manager-finalsite',
   'co-finalsite',
   'Finalsite is looking for an experienced Project Manager to oversee digital projects for K-12 school districts. You will coordinate cross-functional teams, manage timelines, and deliver client projects on budget.',
   60000, 85000, 'USD',
   'https://careers.jobscore.com/careers/finalsite/jobs/project-manager-cDf7byUq1adQPyKK6YEQyZ',
   'cat-pm', 'full-time',
   ARRAY['project-management', 'edtech'],
   ARRAY['Remote USA'],
   false, false, 'live', 'manual', false,
   now(), now() + interval '30 days'),

  ('Partner Account Management',
   'partner-account-management-jumpcloud',
   'co-jumpcloud',
   'JumpCloud is hiring a Partner Account Manager to grow and manage channel partner relationships across Latin America. Drive revenue through our partner ecosystem in Brazil and surrounding markets.',
   null, null, 'USD',
   'https://jobs.lever.co/jumpcloud/0f12db70-b4ec-4238-89db-dbdbcacd08a6',
   'cat-sales', 'full-time',
   ARRAY['sales', 'saas', 'account-management', 'partnerships'],
   ARRAY['Remote Brazil'],
   false, false, 'live', 'manual', false,
   now(), now() + interval '30 days'),

  ('Demand Generation Program Manager',
   'demand-generation-program-manager-grafana',
   'co-grafana',
   'Grafana Labs is seeking a Demand Generation Program Manager to build and execute multi-channel demand programs that drive pipeline. Own campaign strategy, ABM programs, and performance reporting.',
   null, null, 'USD',
   'https://job-boards.greenhouse.io/grafanalabs/jobs/6115636004',
   'cat-mktg', 'full-time',
   ARRAY['marketing', 'demand-gen', 'b2b'],
   ARRAY['Remote Canada'],
   false, false, 'live', 'manual', false,
   now(), now() + interval '30 days'),

  ('Gaming Support Agent',
   'gaming-support-agent-5ca',
   'co-5ca',
   '5CA is hiring Gaming Support Agents to provide player support for leading gaming titles. Handle tickets, live chat, and community management. GMT+3 timezone overlaps well with Asia working hours.',
   null, null, 'USD',
   'https://jobs.5ca.com/jobs?gh_jid=4727142101',
   'cat-support', 'full-time',
   ARRAY['entry-level', 'gaming', 'support', 'customer-service'],
   ARRAY['Remote Serbia', 'Remote Bosnia', 'Remote Turkey'],
   false, false, 'live', 'manual', true,
   now(), now() + interval '30 days'),

  ('Recruiter EMEA',
   'recruiter-emea-airbnb',
   'co-airbnb',
   'Airbnb is looking for an experienced EMEA Recruiter to support hiring across the UK and Ireland. Partner with business leaders to attract top talent and build scalable recruiting processes.',
   null, null, 'GBP',
   'https://careers.airbnb.com/positions/8066760/?gh_jid=8066760',
   'cat-hr', 'full-time',
   ARRAY['recruiting', 'hr', 'talent-acquisition'],
   ARRAY['Remote UK', 'Remote Ireland'],
   false, false, 'live', 'manual', false,
   now(), now() + interval '30 days'),

  ('Customer Support Engineer',
   'customer-support-engineer-makersite',
   'co-makersite',
   'Makersite is hiring a Customer Support Engineer to help enterprise customers adopt our sustainability intelligence platform. Provide technical guidance, resolve complex issues, and become a product expert.',
   70000, 80000, 'EUR',
   'https://makersitegmbh.recruitee.com/o/sustainability-consultant-us-mfx-2',
   'cat-tech-support', 'full-time',
   ARRAY['technical-support', 'sustainability', 'enterprise', 'saas'],
   ARRAY['Remote Europe'],
   true, false, 'live', 'manual', false,
   now(), now() + interval '30 days'),

  ('Enterprise Demand Generation',
   'enterprise-demand-generation-elevenlabs',
   'co-elevenlabs',
   'ElevenLabs is hiring an Enterprise Demand Generation specialist to drive pipeline for our AI voice platform. Build account-based marketing programs targeting enterprise buyers globally, including APAC.',
   null, null, 'USD',
   'https://jobs.ashbyhq.com/elevenlabs/e8cf6379-6a95-4317-a7fd-52028510f432',
   'cat-mktg', 'full-time',
   ARRAY['marketing', 'ai', 'enterprise', 'abm'],
   ARRAY['Remote Worldwide'],
   true, true, 'live', 'manual', true,
   now(), now() + interval '30 days'),

  ('Enterprise Support Specialist',
   'enterprise-support-specialist-soundstack',
   'co-soundstack',
   'SoundStack is looking for an Enterprise Support Specialist to own the post-sale support experience for our largest customers. Triage escalations, drive resolution, and build internal knowledge bases.',
   null, null, 'USD',
   'https://jobs.lever.co/SoundStack/c5fd4335-881b-48f5-aa41-05ffba63a69b',
   'cat-tech-support', 'full-time',
   ARRAY['technical-support', 'enterprise', 'audio-tech'],
   ARRAY['Remote USA'],
   true, false, 'live', 'manual', false,
   now(), now() + interval '30 days'),

  ('Payroll & Benefits Specialist',
   'payroll-benefits-specialist-varicent',
   'co-varicent',
   'Varicent is hiring a Payroll & Benefits Specialist to manage payroll processing and employee benefits administration for Latin America. Strong knowledge of Costa Rica employment law preferred.',
   null, null, 'USD',
   'https://job-boards.greenhouse.io/varicent/jobs/5310643008',
   'cat-finance', 'full-time',
   ARRAY['payroll', 'benefits', 'hr', 'finance'],
   ARRAY['Remote Costa Rica'],
   true, false, 'live', 'manual', false,
   now(), now() + interval '30 days'),

  ('Customer Success Manager',
   'customer-success-manager-enode',
   'co-enode',
   'Enode is seeking a Customer Success Manager to help energy technology customers get maximum value from our platform. Drive adoption, renewals, and expansion across the European market.',
   null, null, 'USD',
   'https://jobs.ashbyhq.com/enode/3def5099-9ccc-4ea8-97ef-f8e7a9f04990',
   'cat-cs', 'full-time',
   ARRAY['customer-success', 'energy-tech', 'saas'],
   ARRAY['Remote Europe'],
   true, false, 'live', 'manual', false,
   now(), now() + interval '30 days'),

  ('Customer Service Manager',
   'customer-service-manager-mny-ventures',
   'co-mny',
   'MNY Ventures is hiring a Customer Service Manager for a high-growth subscription e-commerce brand. Lead a remote support team, design customer service playbooks, and own CSAT metrics. Fully remote worldwide — ideal for anyone based in Asia.',
   null, null, 'USD',
   'https://rosabella.applytojob.com/apply/163z9GGyu6/Customer-Service-Manager-HighGrowth-Subscription-Ecommerce-Brand',
   'cat-mgmt', 'full-time',
   ARRAY['management', 'customer-service', 'ecommerce', 'subscription'],
   ARRAY['Remote Worldwide'],
   true, false, 'live', 'manual', true,
   now(), now() + interval '30 days');
